version: '3.9'

services:

  lite-bank_account:
    container_name: lite-bank_account
    image: lite-bank_account
    environment:
      APP_PORT: 8081
      START_ID: 100
    ports:
      - "8001:8081"
    build:
      context: ./
      dockerfile: account/Dockerfile
    cpu_count: 8

  lite-bank_cashbacks:
    container_name: lite-bank_cashbacks
    image: lite-bank_cashbacks
    environment:
      APP_PORT: 8081
      CATEGORY: 2
      PERCENTAGE: 10
      KAFKA_PORT: 9092
    ports:
      - "8002:8081"
    build:
      context: ./
      dockerfile: cashback/Dockerfile

  lite-bank_fee:
    container_name: lite-bank_fee
    image: lite-bank_fee
    environment:
      APP_PORT: 8081
    ports:
      - "8003:8081"
    build:
      context: ./
      dockerfile: commission/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.00'

  lite-bank_operations:
    container_name: lite-bank_operations
    image: lite-bank_operations
    environment:
      APP_PORT: 8081
    ports:
      - "8004:8081"
    build:
      context: ./
      dockerfile: operations/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.00'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -Xms128m -Xmx256m
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_HOSTNAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
